ATTACH TABLE _ UUID 'cee134dd-b6e3-492d-bf37-3a3ab0119f31'
(
    `token_address` LowCardinality(String),
    `pair_address` LowCardinality(String) DEFAULT '',
    `token_symbol` String,
    `token_name` String,
    `chain` LowCardinality(String) DEFAULT 'BSC',
    `pair_created_block` UInt64 DEFAULT 0,
    `pair_created_ts` UInt64 DEFAULT 0,
    `first_kol_buy_ts` UInt64 DEFAULT 0,
    `token_age_at_buy_sec` UInt64 DEFAULT 0,
    `initial_liq_bnb` Float64 DEFAULT 0,
    `initial_liq_usd` Float64 DEFAULT 0,
    `price_at_entry` Float64 DEFAULT 0,
    `is_open_source` UInt8 DEFAULT 0,
    `is_proxy` UInt8 DEFAULT 0,
    `is_honeypot` UInt8 DEFAULT 0,
    `buy_tax` Float32 DEFAULT 0,
    `sell_tax` Float32 DEFAULT 0,
    `is_mintable` UInt8 DEFAULT 0,
    `has_blacklist` UInt8 DEFAULT 0,
    `can_take_ownership` UInt8 DEFAULT 0,
    `owner_change_balance` UInt8 DEFAULT 0,
    `hidden_owner` UInt8 DEFAULT 0,
    `selfdestruct` UInt8 DEFAULT 0,
    `external_call` UInt8 DEFAULT 0,
    `is_renounced` UInt8 DEFAULT 0,
    `holder_count` UInt32 DEFAULT 0,
    `top10_holder_pct` Float32 DEFAULT 0,
    `creator_pct` Float32 DEFAULT 0,
    `lp_locked` UInt8 DEFAULT 0,
    `lp_lock_pct` Float32 DEFAULT 0,
    `buy_count_5m` UInt32 DEFAULT 0,
    `sell_count_5m` UInt32 DEFAULT 0,
    `unique_buyers_5m` UInt32 DEFAULT 0,
    `volume_usd_5m` Float64 DEFAULT 0,
    `deployer_address` LowCardinality(String) DEFAULT '',
    `deployer_total_tokens` UInt32 DEFAULT 0,
    `deployer_rug_count` UInt32 DEFAULT 0,
    `deployer_avg_lifespan_h` Float32 DEFAULT 0,
    `kol_buyer_count` UInt8 DEFAULT 0,
    `kol_wallets` String DEFAULT '',
    `honeypot_sim_success` UInt8 DEFAULT 0,
    `honeypot_buy_tax` Float32 DEFAULT 0,
    `honeypot_sell_tax` Float32 DEFAULT 0,
    `updated_at` DateTime64(3) DEFAULT now64(3)
)
ENGINE = ReplacingMergeTree(updated_at)
ORDER BY token_address
SETTINGS index_granularity = 8192
